version: "1.0"
name: 流水线-202608171544
displayName: 流水线-202608171544
stages:
- name: 未命名
  displayName: 未命名
  strategy: naturally
  trigger: auto
  steps:
  - step: build@golang
    name: 6d293f4c
    displayName: Golang 构建
    golangVersion: "1.24"
    commands:
    - "# 默认使用goproxy.cn\\n export GOPROXY=https://goproxy.cn\\n # 输入你的构建命令 make build"
    artifacts: []
    caches:
    - /go/pkg/mod
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"
triggers:
  trigger: auto
  push:
    branches:
      prefix:
      - dev
      precise: []
      include: []
notify: []
