CREATE TABLE site_analysis_task (
  id                   BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT  COMMENT '主键',
  source_type          TINYINT UNSIGNED NOT NULL DEFAULT 1       COMMENT '来源类型：1问卷 2外部表 3API',
  source_submission_id BIGINT UNSIGNED  NOT NULL DEFAULT 0       COMMENT '来源提交记录 ID',
  source_updated_at    INT UNSIGNED     NOT NULL DEFAULT 0       COMMENT '来源记录更新时间快照（Unix 时间戳）',
  site_name            VARCHAR(128)     NOT NULL DEFAULT ''      COMMENT '站点名称',
  site_address         VARCHAR(255)     NOT NULL DEFAULT ''      COMMENT '站点地址',
  longitude            DECIMAL(10,6)    NOT NULL DEFAULT 0.000000 COMMENT '经度',
  latitude             DECIMAL(10,6)    NOT NULL DEFAULT 0.000000 COMMENT '纬度',
  status               TINYINT UNSIGNED NOT NULL DEFAULT 1       COMMENT '任务状态：1待执行 2执行中 3已完成 4失败',
  current_step_code    TINYINT UNSIGNED NOT NULL DEFAULT 1       COMMENT '当前步骤编码：1至7',
  priority             TINYINT UNSIGNED NOT NULL DEFAULT 0       COMMENT '任务优先级，数值越大优先级越高',
  attempt_count        INT UNSIGNED     NOT NULL DEFAULT 0       COMMENT 'Worker 成功领取任务次数',
  locked_by            VARCHAR(64)      NOT NULL DEFAULT ''      COMMENT '当前 Worker 标识',
  locked_at            INT UNSIGNED     NOT NULL DEFAULT 0       COMMENT '任务领取时间（Unix 时间戳）',
  heartbeat_at         INT UNSIGNED     NOT NULL DEFAULT 0       COMMENT 'Worker 最近心跳时间（Unix 时间戳）',
  started_at           INT UNSIGNED     NOT NULL DEFAULT 0       COMMENT '任务首次开始时间（Unix 时间戳）',
  completed_at         INT UNSIGNED     NOT NULL DEFAULT 0       COMMENT '任务完成时间（Unix 时间戳）',
  error_code           VARCHAR(64)      NOT NULL DEFAULT ''      COMMENT '任务错误码',
  error_message        TEXT             NOT NULL DEFAULT ('')    COMMENT '任务错误信息',
  created_at           INT UNSIGNED     NOT NULL DEFAULT 0       COMMENT '创建时间（Unix 时间戳）',
  updated_at           INT UNSIGNED     NOT NULL DEFAULT 0       COMMENT '更新时间（Unix 时间戳）',
  PRIMARY KEY (id),
  KEY idx_source_submission_status (source_type, source_submission_id, status),
  KEY idx_status_priority_created (status, priority, created_at),
  KEY idx_status_heartbeat (status, heartbeat_at),
  KEY idx_status_started (status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='单站分析任务表';
