CREATE TABLE agent_execution_log (
  id                   BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT COMMENT '主键',
  workflow_run_id      BIGINT UNSIGNED  NOT NULL DEFAULT 0      COMMENT 'Agent 工作流运行记录 ID',
  task_id              BIGINT UNSIGNED  NOT NULL DEFAULT 0      COMMENT '单站分析任务 ID',
  step_code            TINYINT UNSIGNED NOT NULL DEFAULT 0      COMMENT '步骤编码：1至7',
  runtime_config_id    BIGINT UNSIGNED  NOT NULL DEFAULT 0      COMMENT 'Agent 运行配置 ID',
  step_execution_count INT UNSIGNED     NOT NULL DEFAULT 0      COMMENT '业务步骤执行轮次',
  model_attempt        INT UNSIGNED     NOT NULL DEFAULT 1      COMMENT '当前步骤执行轮次内的模型请求序号',
  repair_attempt       TINYINT(1)       NOT NULL DEFAULT 0      COMMENT '是否结构化结果修复请求：1是 0否',
  status               TINYINT UNSIGNED NOT NULL DEFAULT 1      COMMENT '调用状态：1执行中 2已完成 3失败 4未知 5取消',
  duration_ms          INT UNSIGNED     NOT NULL DEFAULT 0      COMMENT '调用耗时（毫秒）',
  provider             VARCHAR(64)      NOT NULL DEFAULT ''     COMMENT '模型供应商快照',
  model                VARCHAR(128)     NOT NULL DEFAULT ''     COMMENT '模型名称快照',
  prompt_version       VARCHAR(64)      NOT NULL DEFAULT ''     COMMENT 'Prompt 版本快照',
  input_tokens         INT UNSIGNED     NOT NULL DEFAULT 0      COMMENT '输入 Token 数',
  output_tokens        INT UNSIGNED     NOT NULL DEFAULT 0      COMMENT '输出 Token 数',
  total_tokens         INT UNSIGNED     NOT NULL DEFAULT 0      COMMENT '总 Token 数',
  usage_available      TINYINT(1)       NOT NULL DEFAULT 0      COMMENT '是否返回 Token Usage：1是 0否',
  finish_reason        VARCHAR(64)      NOT NULL DEFAULT ''     COMMENT '模型结束原因',
  error_code           VARCHAR(64)      NOT NULL DEFAULT ''     COMMENT '调用错误码',
  error_message        TEXT             NOT NULL DEFAULT ('')   COMMENT '调用错误信息',
  trace_id             VARCHAR(64)      NOT NULL DEFAULT ''     COMMENT 'LangSmith Trace ID',
  run_id               VARCHAR(64)      NOT NULL DEFAULT ''     COMMENT 'LangSmith Run ID',
  created_at           INT UNSIGNED     NOT NULL DEFAULT 0      COMMENT '创建时间（Unix 时间戳）',
  updated_at           INT UNSIGNED     NOT NULL DEFAULT 0      COMMENT '更新时间（Unix 时间戳）',
  PRIMARY KEY (id),
  UNIQUE KEY uk_workflow_step_execution_attempt (workflow_run_id, step_code, step_execution_count, model_attempt),
  KEY idx_task_step_created (task_id, step_code, created_at),
  KEY idx_workflow_status (workflow_run_id, status),
  KEY idx_trace_id (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Agent 模型调用日志表';
