CREATE TABLE `site_exploration_site` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态：1待勘探 2待补充 3已勘探 4已签约 5建设中 6建设完成 7运营中',
  `explorer_name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '勘探人姓名',
  `exploration_team` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '勘探小组',
  `exploration_date` CHAR(10) NOT NULL DEFAULT '' COMMENT '勘探业务日期，格式YYYY-MM-DD',
  `overall_score` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '综合得分：0未评分 1至100已评分',
  `selection_recommendation` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '选址建议：0无 1补充资料后复评 2优先推进 3建议推进 4谨慎推进 5暂缓推进',
  `project_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '项目名称',
  `contact_name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '场站联系人姓名',
  `contact_phone_encrypted` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '场站联系人电话密文',
  `province_city` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '所在地级市',
  `county_district` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '所在区县',
  `location_address` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '项目详细地理位置',
  `longitude` DECIMAL(10,6) NOT NULL DEFAULT 0.000000 COMMENT 'WGS84经度',
  `latitude` DECIMAL(9,6) NOT NULL DEFAULT 0.000000 COMMENT 'WGS84纬度',
  `satellite_images` JSON NOT NULL DEFAULT (JSON_ARRAY()) COMMENT '场站位置卫星图元数据JSON数组',
  `highway_distance_meters` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '距离高速口距离，单位米',
  `site_area_square_meters` DECIMAL(12,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT '场站面积，单位平方米',
  `arterial_road_distance_meters` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '距离国省主干道通道距离，单位米',
  `access_convenience` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '进出便利性：0未填写 1很好 2较好 3一般',
  `access_convenience_images` JSON NOT NULL DEFAULT (JSON_ARRAY()) COMMENT '进出便利性现场图片元数据JSON数组',
  `land_qualified` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '土地性质是否满足建设要求：1是 0否',
  `land_type` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '土地性质：0无 1建设用地 2集体经营性用地 3划拨用地 4其他',
  `land_type_description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '其他土地性质说明',
  `has_land_proof` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否有土地证明材料：1是 0否',
  `has_lease_agreement` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否有土地租赁协议：1是 0否',
  `land_scene_images` JSON NOT NULL DEFAULT (JSON_ARRAY()) COMMENT '现场土地情况图片元数据JSON数组',
  `has_other_structures` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否有其他附属物：1是 0否',
  `other_structure_images` JSON NOT NULL DEFAULT (JSON_ARRAY()) COMMENT '其他附属物图片元数据JSON数组',
  `ground_hardening` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '地面硬化条件：0未填写 1较好无需硬化 2一般需要硬化 3无硬化',
  `terrain_condition` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '土地地势：0未填写 1地势较高排水良好 2平坦不易积水 3低洼易积水',
  `capacity_description` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '周边接入点及容量情况',
  `transport_capacity_description` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '车流量、厂区及新能源重卡运力情况',
  `has_nearby_truck_charging_station` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '五公里内是否有新能源重卡充电站：1是 0否',
  `nearby_truck_charging_station_description` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '附近新能源重卡充电站数量及名称',
  `cooperation_mode` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '合作模式：0未填写 1服务费分成 2场站净利润分成 3固定租金',
  `cooperation_terms` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '合作比例或租金条件',
  `site_maturity` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '场站成熟度：0未填写 1A类 2B类 3C类',
  `important_notes` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '其他重要事项',
  `created_by_member_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建平台成员主键',
  `updated_by_member_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '最后更新平台成员主键',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间（Unix 时间戳）',
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间（Unix 时间戳）',
  PRIMARY KEY (`id`),
  KEY `idx_site_exploration_updated` (`updated_at`, `id`),
  KEY `idx_site_exploration_status_updated` (`status`, `updated_at`, `id`),
  KEY `idx_site_exploration_team_updated` (`exploration_team`, `updated_at`, `id`),
  KEY `idx_site_exploration_city_updated` (`province_city`, `updated_at`, `id`),
  KEY `idx_site_exploration_project` (`project_name`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='勘探站点';
