CREATE TABLE `site_analysis_task` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `exploration_site_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '勘探站点主键',
  `creation_request_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '任务创建请求唯一标识',
  `created_by_member_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建任务的平台成员主键',
  `input_snapshot_json` MEDIUMTEXT NOT NULL DEFAULT ('{}') COMMENT '分析输入快照JSON',
  `workflow_version` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '分析工作流版本',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '任务状态：1待执行 2执行中 3已完成 4失败',
  `current_step_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '当前分析步骤编码',
  `overall_score` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '综合得分：0至100，0为有效分析结果',
  `selection_recommendation` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '选址建议：0无 1补充资料后复评 2优先推进 3建议推进 4谨慎推进 5暂缓推进',
  `overall_summary` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '综合分析摘要',
  `locked_by` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '当前Worker标识',
  `locked_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '任务领取时间（Unix 时间戳）',
  `heartbeat_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Worker最近心跳时间（Unix 时间戳）',
  `error_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '任务错误码',
  `redacted_error_message` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '已脱敏任务错误信息',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间（Unix 时间戳）',
  `started_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '首次开始时间（Unix 时间戳）',
  `completed_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '完成时间（Unix 时间戳）',
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间（Unix 时间戳）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_analysis_task_request_site` (`creation_request_id`, `exploration_site_id`),
  KEY `idx_site_analysis_task_claim_queued` (`status`, `created_at`, `id`),
  KEY `idx_site_analysis_task_claim_stale` (`status`, `heartbeat_at`, `created_at`, `id`),
  KEY `idx_site_analysis_task_site_history` (`exploration_site_id`, `created_at`, `id`),
  KEY `idx_site_analysis_task_work_recent` (`updated_at` DESC, `id` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='勘探站点分析任务';
