CREATE TABLE `site_analysis_step` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '分析任务主键',
  `step_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '分析步骤编码',
  `step_order` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '步骤执行顺序',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '步骤状态：1待执行 2执行中 3已完成 4失败',
  `score` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '步骤得分：0至100，0为有效分析结果',
  `summary` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '步骤分析摘要',
  `risks_json` MEDIUMTEXT NOT NULL DEFAULT ('[]') COMMENT '步骤风险项JSON数组',
  `error_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '步骤错误码',
  `redacted_error_message` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '已脱敏步骤错误信息',
  `started_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '步骤开始时间（Unix 时间戳）',
  `completed_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '步骤完成时间（Unix 时间戳）',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间（Unix 时间戳）',
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间（Unix 时间戳）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_analysis_step_task_code` (`task_id`, `step_code`),
  KEY `idx_site_analysis_step_task_order` (`task_id`, `step_order`, `id`),
  KEY `idx_site_analysis_step_work_recent` (`status`, `updated_at` DESC, `task_id` DESC, `step_code` ASC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='勘探站点分析步骤';
