ALTER TABLE `site_exploration_site`
  ADD COLUMN `power_access_method` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '电源接入方式：0未选择，1为10kV，2为0.4kV',
  ADD COLUMN `electricity_nature` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用电性质：0未选择，1工业，2商业',
  ADD COLUMN `high_voltage_access_method` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '高压接入方式：0未选择，1新建箱变，2配电室',
  ADD COLUMN `ten_kv_line_access_distance_meters` DECIMAL(12,2) UNSIGNED NULL COMMENT '10kV线路接入距离（米）',
  ADD COLUMN `competitor_one_scale` TEXT NOT NULL DEFAULT ('') COMMENT '周边竞争对手一规模',
  ADD COLUMN `competitor_one_model_quantity` TEXT NOT NULL DEFAULT ('') COMMENT '周边竞争对手一型号及数量',
  ADD COLUMN `competitor_one_utilization_rate` TEXT NOT NULL DEFAULT ('') COMMENT '周边竞争对手一使用率',
  ADD COLUMN `competitor_one_electricity_price` TEXT NOT NULL DEFAULT ('') COMMENT '周边竞争对手一电费',
  ADD COLUMN `competitor_two_scale` TEXT NOT NULL DEFAULT ('') COMMENT '周边竞争对手二规模',
  ADD COLUMN `competitor_two_model_quantity` TEXT NOT NULL DEFAULT ('') COMMENT '周边竞争对手二型号及数量',
  ADD COLUMN `competitor_two_utilization_rate` TEXT NOT NULL DEFAULT ('') COMMENT '周边竞争对手二使用率',
  ADD COLUMN `competitor_two_electricity_price` TEXT NOT NULL DEFAULT ('') COMMENT '周边竞争对手二电费',
  ADD COLUMN `survey_recommendation` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '踏勘建议：0未选择，1优先建设，2项目可建，3项目储备，4建议放弃',
  ADD COLUMN `charging_pile_model` TEXT NOT NULL DEFAULT ('') COMMENT '充电桩型号',
  ADD COLUMN `charging_pile_quantity` INT UNSIGNED NULL COMMENT '充电桩数量',
  ADD COLUMN `transformer_capacity` TEXT NOT NULL DEFAULT ('') COMMENT '变压器容量',
  ADD COLUMN `transformer_quantity` INT UNSIGNED NULL COMMENT '变压器数量',
  ADD COLUMN `preliminary_design_notes` TEXT NOT NULL DEFAULT ('') COMMENT '现场初步设计其他备注';
